name: UnitTest

on:
  push:
    paths:
      - 'src/**'
  pull_request:
jobs:
  unit-test:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./src/requirements.txt
      - name: Execute tests
        run: |
          cd ./src/
          python -m test
